[package]
name = "async-dispatcher"
version = "0.1.0"
edition = "2021"

[features]
"test-macro" = ["async-dispatcher-macros"]

[dependencies]
async-task = "4.7"
futures-lite = "1"
async-dispatcher-macros = { path = "./macros", version = "0.1.0", optional = true }
