[package]
name = "async-dispatcher-macros"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
description = "Convenience macros for async-dispatcher"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
